nameOverride: nfs
persistence:
  enabled: true
  storageClass: local-path
  size: 200Mi
  accessMode: ReadWriteOnce

storageClass:
  defaultClass: false
  provisionerName: nfs

nodeSelector:
  kubernetes.io/hostname: k3d-nfs-test-server-0