---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-0
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
  claimRef:
    namespace: default
    name: data-nfs-0
