### The PVC used by the sample deployment defined in 
### 'deployment-echo.yaml'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-for-pods
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi