name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installl dependencies
        run: |
          sudo apt-get install -y curl make
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

      - name: Spin up K3D and deploy test workload
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update
          make all
